const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
async function overflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();}
async function shot(page,info,name){fs.mkdirSync('screenshots',{recursive:true});await page.screenshot({path:path.resolve('screenshots',info.project.name+'-systems-'+name+'.png'),fullPage:true});}
test('inference inputs and selected request change the computed comparison',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/labs/inference-topology/');await expect(page.locator('#view-lab h1')).toHaveText('Inference topology');await expect(page.locator('[data-sys-layout]')).toHaveCount(2);
 const first=await page.locator('.systems-verdict').innerText();await page.locator('[data-sys-preset="decode"]').click();expect(await page.locator('.systems-verdict').innerText()).not.toBe(first);await page.locator('[data-sys-input="gpus"]').selectOption('2');await expect(page.locator('[data-sys-input="encoders"] option')).toHaveCount(1);await page.locator('[data-sys-request]').selectOption('0');await expect(page.locator('.systems-waterfall').first()).toHaveAttribute('aria-label','Request 1 timeline');await overflow(page);
 await page.locator('[data-sys-preset="media"]').click();await shot(page,info,'inference');expect(errors).toEqual([]);
});
test('ambiguous tool commit recovers with an idempotent effect and exposes the unsafe outcome',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/labs/agent-recovery/');await page.locator('[data-recover="ambiguous"]').click();await expect(page.locator('.systems-verdict')).toContainText('Worker unavailable');await expect(page.locator('[data-recovery-writes]')).toHaveText('1 write');await expect(page.locator('[data-recover="step"]')).toBeDisabled();await page.locator('[data-recover="resume"]').click();for(let i=0;i<4;i++)await page.locator('[data-recover="step"]').click();await expect(page.locator('.systems-verdict')).toContainText('Session completed');await expect(page.locator('.systems-verdict')).toContainText('2 tool deliveries · 1 external write');await shot(page,info,'recovery-safe');
 await page.locator('[data-recovery-safe]').uncheck();await page.locator('[data-recover="ambiguous"]').click();await page.locator('[data-recover="resume"]').click();for(let i=0;i<4;i++)await page.locator('[data-recover="step"]').click();await expect(page.locator('[data-recovery-writes]')).toHaveText('2 writes');await expect(page.locator('.systems-verdict')).toContainText('duplicate external write');await page.locator('[data-recovery-span="4"]').click();await expect(page.locator('.recovery-inspector')).toContainText('Worker lost');await overflow(page);await shot(page,info,'recovery-unsafe');expect(errors).toEqual([]);
});
test('new notes remain concise, link back to experience and have readable static lab pages',async({page,browser},info)=>{
 await page.goto('/#notes');await expect(page.locator('#notes-list .article-card')).toHaveCount(12);await expect(page.locator('#view-notes > .actions')).toContainText('Experience & roles');await expect(page.locator('#paper-count')).toHaveText('31 references');
 for(const slug of ['inference-topology','agent-recovery']){await page.goto('/notes/'+slug+'/');await expect(page.locator('.article-section')).toHaveCount(5);expect((await page.locator('.article-prose').innerText()).split(/\s+/).length).toBeLessThan(600);await expect(page.locator('#article-widget a')).toHaveAttribute('href','/labs/'+slug+'/');await overflow(page);}
 await shot(page,info,'note');
 const context=await browser.newContext({javaScriptEnabled:false,baseURL:test.info().project.use.baseURL||'http://127.0.0.1:4173'}),p=await context.newPage();
 for(const slug of ['inference-topology','agent-recovery']){await p.goto('/notes/'+slug+'/');await expect(p.locator('.article-section')).toHaveCount(5);await p.goto('/labs/'+slug+'/');await expect(p.locator('.systems-lab')).toBeVisible();await expect(p.locator('link[rel="canonical"]')).toHaveAttribute('href','https://jorgeutd.github.io/labs/'+slug+'/');}
 await context.close();
});
test('route changes, keyboard controls, dark theme and reduced motion preserve the labs',async({page,isMobile},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#lab/agent-recovery');await page.locator('[data-recover="step"]').focus();await page.keyboard.press('Enter');await expect(page.locator('.recovery-log li')).toHaveCount(1);
 if(isMobile)await page.locator('#menu-toggle').click();await page.locator('#theme-toggle').click();if(isMobile)await page.locator('#scrim').click({position:{x:page.viewportSize().width-10,y:30}});await page.locator('[data-recover="ambiguous"]').click();await overflow(page);await shot(page,info,'recovery-dark');
 await page.goto('/#demos');await expect(page.locator('.systems-new article')).toHaveCount(2);await page.locator('.systems-new a[href="/labs/inference-topology/"]').click();await expect(page.locator('.systems-lab')).toHaveCount(1);await overflow(page);await shot(page,info,'inference-dark');await page.goto('/#research');await expect(page.locator('#research-transformer-slot #transformer-anatomy')).toHaveCount(1);expect(errors).toEqual([]);
});
